### ISSUE TITLE
log4j specific logger

### ISSUE THREAD

**Issue by Kaucher90** [cologneintelligence/FitGoodies#22]
The SetupFixture for log4j has a problem for specific loggers (which had to be registrated by the "monitor"-clause).

<strong>usage scenario</strong>
=== log4j.properties ===
log4j.appender.Stdout=org.apache.log4j.ConsoleAppender
log4j.appender.Stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.Stdout.layout.ConversionPattern=%d{HH:mm:ss.SSS} %p %c | %m%n

log4j.rootLogger=INFO
log4j.logger.org.example.MyClass=INFO
=== setup.html ===
<table>
<tr><td>de.cologneintelligence.fitgoodies.log4j.SetupFixture</td></tr>
<tr><td>monitorRoot</td><td>Stdout</td></tr>
<tr><td>monitor</td><td>org.example.MyClass</td><td>Stdout</td></tr>
</table>

<strong>error</strong>
de.cologneintelligence.fitgoodies.log4j.SetupFixture java.lang.NullPointerException 
at de.cologneintelligence.fitgoodies.log4j.CaptureAppender.&lt;init>(CaptureAppender.java:42)
at de.cologneintelligence.fitgoodies.log4j.CaptureAppender.newAppenderFrom(CaptureAppender.java:110)
at de.cologneintelligence.fitgoodies.log4j.LogHelper.addCaptureToLogger(LogHelper.java:39)
at de.cologneintelligence.fitgoodies.log4j.SetupFixture.addRootMonitor(SetupFixture.java:110)
at de.cologneintelligence.fitgoodies.log4j.SetupFixture.processRowWithMonitorRoot(SetupFixture.java:105)
at de.cologneintelligence.fitgoodies.log4j.SetupFixture.processRowWithCommand(SetupFixture.java:79)
at de.cologneintelligence.fitgoodies.log4j.SetupFixture.doCells(SetupFixture.java:74)<br />
...

**Comment by thomas3** [comment]
Further inspection of this issue revealed a wrong log4j configuration. Fixing this lead to the desired behaviour.
